import { writeFileSync } from 'fs';

const content = [
  `import {`,
  `  escapeHtml,`,
  `  formatDateTime,`,
  `  formatPercent,`,
  `} from "../../core/formatters.js";`,
  `import { renderAvatar, renderReputationBadge } from "../authors/renderers.js";`,
  ``,
  `export function renderProfileView(target, profile, { isAvatarBusy = false } = {}) {`,
  `  if (!target) {`,
  `    return;`,
  `  }`,
  ``,
  `  const approvalPercentage = Number(profile.privateMetrics?.score ?? 0);`,
  `  const totalReviews = profile.privateMetrics?.totalReviews ?? 0;`,
  `  const hasAvatar = Boolean(profile.avatarUrl);`,
  `  const reviewLabel = totalReviews === 1 ? "avaliacao recebida" : "avaliacoes recebidas";`,
  ``,
  "  target.innerHTML = `",
  `    <section class="profile-card">`,
  ``,
  `      <div class="profile-hero">`,
  `        <div class="profile-avatar-shell">`,
  "          ${renderAvatar({",
  `            avatarUrl: profile.avatarUrl,`,
  `            username: profile.username,`,
  "            alt: `Foto de perfil de @${profile.username}`,",
  `            className: "profile-avatar-image",`,
  `          })}`,
  `          <span class="profile-privacy-badge">`,
  `            <svg width="12" height="12" viewBox="0 0 16 16" fill="none" aria-hidden="true">`,
  `              <path d="M8 1C5.24 1 3 3.24 3 6v1H2a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V8a1 1 0 0 0-1-1h-1V6c0-2.76-2.24-5-5-5zm0 1.5A3.5 3.5 0 0 1 11.5 6v1h-7V6A3.5 3.5 0 0 1 8 2.5zM8 10a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3z" fill="currentColor"/>`,
  `            </svg>`,
  `            Perfil privado`,
  `          </span>`,
  `        </div>`,
  ``,
  `        <div class="profile-identity">`,
  `          <div class="profile-heading">`,
  "            <h2 class=\"profile-username\">@${escapeHtml(profile.username)}</h2>",
  "            ${renderReputationBadge(profile.publicReputation, \"reputation-badge-large\")}",
  `          </div>`,
  `          <p class="profile-privacy-copy">Apenas foto, nome e reputacao sao visiveis publicamente.</p>`,
  ``,
  `          <dl class="profile-meta-grid">`,
  `            <div class="profile-meta-item">`,
  `              <dt>Email</dt>`,
  "              <dd>${escapeHtml(profile.email)}</dd>",
  `            </div>`,
  `            <div class="profile-meta-item">`,
  `              <dt>Papel</dt>`,
  "              <dd>${escapeHtml(profile.role)}</dd>",
  `            </div>`,
  `            <div class="profile-meta-item">`,
  `              <dt>Membro desde</dt>`,
  "              <dd>${escapeHtml(formatDateTime(profile.createdAt))}</dd>",
  `            </div>`,
  `          </dl>`,
  `        </div>`,
  `      </div>`,
  ``,
  `      <div class="profile-panels">`,
  `        <article class="profile-panel metric-panel">`,
  `          <h3 class="profile-panel-title">Reputacao</h3>`,
  `          <div class="metric-score">`,
  "            <span class=\"metric-value status-neutral\">${escapeHtml(formatPercent(approvalPercentage))}</span>",
  `            <span class="metric-label">de aprovacao</span>`,
  `          </div>`,
  "          <p class=\"profile-panel-sub\">${escapeHtml(String(totalReviews))} ${reviewLabel}</p>",
  `        </article>`,
  ``,
  `        <article class="profile-panel avatar-panel">`,
  `          <h3 class="profile-panel-title">Foto de perfil</h3>`,
  `          <p class="profile-panel-sub">Visivel no feed e nos comentarios.</p>`,
  ``,
  "          <label",
  "            class=\"avatar-upload-zone ${isAvatarBusy ? 'avatar-upload-zone--busy' : ''}\"",
  "            aria-label=\"Selecionar nova foto de perfil\"",
  "            ${isAvatarBusy ? \"aria-disabled='true'\" : ''}",
  `          >`,
  `            <input`,
  `              type="file"`,
  `              accept="image/jpeg,image/png,image/webp"`,
  `              data-avatar-input`,
  `              class="avatar-upload-input"`,
  "              ${isAvatarBusy ? 'disabled' : ''}",
  `            />`,
  `            <span class="avatar-upload-icon" aria-hidden="true">`,
  `              <svg width="24" height="24" viewBox="0 0 24 24" fill="none">`,
  `                <path d="M12 4a1 1 0 0 1 .78.375l3 3.75A1 1 0 0 1 15 10h-2v7a1 1 0 1 1-2 0v-7H9a1 1 0 0 1-.78-1.625l3-3.75A1 1 0 0 1 12 4z" fill="currentColor"/>`,
  `                <path d="M5 19a1 1 0 1 0 0 2h14a1 1 0 1 0 0-2H5z" fill="currentColor"/>`,
  `              </svg>`,
  `            </span>`,
  `            <span class="avatar-upload-label">`,
  "              ${isAvatarBusy ? 'Enviando...' : (hasAvatar ? 'Trocar foto' : 'Enviar foto')}",
  `            </span>`,
  `            <span class="avatar-upload-hint">JPG, PNG ou WebP &bull; max 5\u00a0MB</span>`,
  `          </label>`,
  ``,
  "          ${",
  `            hasAvatar`,
  "              ? \`<button",
  `                  type="button"`,
  `                  class="btn-remove-avatar"`,
  `                  data-remove-avatar`,
  "                  \${isAvatarBusy ? 'disabled' : ''}",
  `                >`,
  `                  <svg width="14" height="14" viewBox="0 0 16 16" fill="none" aria-hidden="true">`,
  `                    <path d="M6 2a1 1 0 0 0-1 1v1H3a1 1 0 0 0 0 2h.09l.67 7.34A2 2 0 0 0 5.75 15h4.5a2 2 0 0 0 1.99-1.66L12.91 6H13a1 1 0 0 0 0-2h-2V3a1 1 0 0 0-1-1H6zm1 2h2v1H7V4zm-2.09 2h6.18l-.66 7.11a.5.5 0 0 1-.5.39h-4.5a.5.5 0 0 1-.5-.39L4.91 6z" fill="currentColor"/>`,
  `                  </svg>`,
  `                  Remover foto`,
  "                </button>\`",
  `              : ''`,
  `          }`,
  `        </article>`,
  `      </div>`,
  ``,
  `    </section>`,
  "  \`;",
  `}`,
].join('\n');

writeFileSync('src/public/js/features/profile/renderers.js', content, 'utf8');
console.log('Renderer written OK');
