import {
  POST_MEDIA_ALLOWED_MIME_TYPES,
  POST_MEDIA_MAX_FILE_SIZE_BYTES,
  POST_MEDIA_MAX_FILE_SIZE_MB,
} from "./postMedia.js";

const AVATAR_MEDIA_FIELD_NAME = "avatar";
const AVATAR_MEDIA_MAX_ITEMS = 1;

export {
  AVATAR_MEDIA_FIELD_NAME,
  AVATAR_MEDIA_MAX_ITEMS,
  POST_MEDIA_ALLOWED_MIME_TYPES as AVATAR_MEDIA_ALLOWED_MIME_TYPES,
  POST_MEDIA_MAX_FILE_SIZE_BYTES as AVATAR_MEDIA_MAX_FILE_SIZE_BYTES,
  POST_MEDIA_MAX_FILE_SIZE_MB as AVATAR_MEDIA_MAX_FILE_SIZE_MB,
};
